DROP TABLE IF EXISTS queue;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS catalog;

CREATE TABLE room (
	id INTEGER AUTO_INCREMENT,
	room_key VARCHAR(36) NOT NULL,
	url VARCHAR(255) NOT NULL DEFAULT '',
	start_time BIGINT NOT NULL,
	paused BIGINT,
	loop_media BOOLEAN NOT NULL DEFAULT FALSE,
	last_sync BIGINT NOT NULL,
	owner VARCHAR(127) NOT NULL,
	locked BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (id)
);

CREATE TABLE queue (
	id INTEGER AUTO_INCREMENT,
	room_id INTEGER,
	url VARCHAR(255),
	title VARCHAR(255),
	PRIMARY KEY (id),
	FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE
);

CREATE TABLE catalog (
	id INTEGER AUTO_INCREMENT,
	url VARCHAR(255),
	title VARCHAR(255) NOT NULL,
	sort_title VARCHAR(255) NOT NULL,
	cover VARCHAR(255) NOT NULL,
	category ENUM ('movie', 'tv', 'music') NOT NULL,
	series INTEGER REFERENCES catalog (id),
	PRIMARY KEY (id)
);
